### ISSUE TITLE
Name of the FF

### ISSUE THREAD

**Issue by kateryna-goloviznina** [agiliopadua/ilff#12]
Agilio, I have some suggestions on how to improve the readability of the name of the FF. It took a few minutes for me to understand what clandp means. I read it as [klandp] and interpreted it as "Clan DP". You can add underscores (cl_and_p), hyphens (cl-and-p), or remove "and" at all (clp). Thank you.

**Comment by agiliopadua** [comment]
Did you get used to it by now?

**Comment by kateryna-goloviznina** [comment]
I resigned to this new name and now I call it [klandp] in my head and no more CL&P.
