### ISSUE TITLE
TFSI partial charge in bpytfsi and py14tfsi

### ISSUE THREAD

**Issue by tribeniroy** [agiliopadua/ilff#5]
The partial charges for tfsi atoms in tfsi.itp in bpytfsi and py14tfsi folder are different. While in ff.itp in both shows a total charge of -1 (which should be the case), in the individual tfsi.itp files, they do not add up to -1. There seems to be a problem with the partial charges.

**Comment by mattwthompson** [comment]
It looks like those files were contributed by Vitaly Chaban some years ago. You may have better luck as to the source of this discrepancy by contacting him directly
