### ISSUE TITLE
warning: litfsi angle OB-SB-OB 4-2-5 102.57 removed

### ISSUE THREAD

**Issue by tribeniroy** [agiliopadua/ilff#6]
I have adopted the FF for ntf2 (TFSI) from fftool/examples/Trial/il.ff. I am receiving a warning while building the lammps file 'warning: litfsi angle OB-SB-OB 4-2-5 102.57 removed'. Are you aware of the cause for this. It is actually reducing one of the angle types i.e. O-S-O from the data.lmp file and probably due to which pressure fluctuations are high during npt.

**Comment by agiliopadua** [comment]
Maybe in your input geometry the O-S-O angle is too far from 118.5 degrees (equilibrium angle in the force field).
I don't have that problem with ntf2 with geometry from ilff/ntf2.zmat

**Comment by tribeniroy** [comment]
Thanks for the reply. I will check that. 

Best wishes
Tribeni

**Comment by tribeniroy** [comment]
I am using the ntf2 file and the warning disappeared. You were right. My initial geometry was not optimized perhaps.

Thanks
Tribeni Roy
